<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ef0a0212-dedf-42bc-9f3f-e56c9db1cf8c</testSuiteGuid>
   <testCaseLink>
      <guid>66a69f85-2ab9-403a-8b64-dbfcc9bd9503</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01 - Login/Login - Invalid Password - Error</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ff4b6c1-f583-4626-831a-900a8ffa6a91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf96331a-e417-46b9-a2a0-d25ef841ef76</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>05f76cb7-5410-4387-9b5e-b0d1f76e365c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01 - Login/Login - Invalid Username - Error</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f92b7a95-6642-44ed-8867-7c6c3846f99b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>592e9fb8-fc6b-4bf4-97ad-977ff7e2a626</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d8b324c1-4c52-4cf6-a566-41d1eccc123d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01 - Login/Login - Valid Credentials - Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e7d7d66-720c-4375-bd4d-a09dd4db5320</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76aba2be-48d4-424f-bb40-935dd6e9d32f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1696ef7d-17d3-4efa-812f-c8cf88baf4b5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
